### ISSUE TITLE
Support IE hacks

### ISSUE THREAD

**Issue by kaime** [krokis/layla#17]
``` css
#ie {
  color: red
  color: red !important
  _color: red
  *color: red
  +color: red
  *+color: red
  color: red\9
  color: red\0
  color: red\9\0
}
```

http://browserhacks.com/
https://gist.github.com/necolas/983116
http://mathiasbynens.be/demo/css-hacks
